### PR TITLE
[CI] Enable cache

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by Alizter** [comment]
@ejgallego So... to cache or not to cache?

**Comment by ejgallego** [comment]
The problem we had with META and the cache is fixed by #14 , so yes, absolutely we should cache right?

When we bump some dep that will make effect big time.

**Comment by Alizter** [comment]
@ejgallego I ended up accidentally pushing that to main so cache is enabled now.

**Comment by ejgallego** [comment]
Sounds good, let's see some numbers, for example let's push a new version of hydra-games that removes that one thousand annoying warnings.

**Pull request closed without merging**
